# SPDX-License-Identifier: LicenseRef-PolyForm-Strict-1.0.0
# SPDX-FileCopyrightText: Copyright (c) 2026 Parashell, Odin Glynn-Martin
#
# This SPDX license identifier and copyright notice must not be
# removed, altered, or obscured. Doing so is a material breach of
# the PolyForm Strict License 1.0.0 and voids all licenses granted
# to you under it immediately and permanently.

from __future__ import annotations


# exact trace spellings stay centralized so variant tables never duplicate owners
KOwnerSites = {
    1004: "SLDMFCU!uoRVAppearanceProperties::restore+0x3ec",
    1020: "SLDMFCU!uoRVAppearanceProperties::restore+0x3fc",
    1036: "SLDMFCU!uoRVAppearanceProperties::restore+0x40c",
    1052: "SLDMFCU!uoRVAppearanceProperties::restore+0x41c",
    1084: "SLDMFCU!uoRVAppearanceProperties::restore+0x43c",
    1100: "SLDMFCU!uoRVAppearanceProperties::restore+0x44c",
    111: "SLDMFCU!uoRVAppearanceProperties::restore+0x6f",
    1132: "SLDMFCU!uoRVAppearanceProperties::restore+0x46c",
    1164: "SLDMFCU!uoRVAppearanceProperties::restore+0x48c",
    1180: "SLDMFCU!uoRVAppearanceProperties::restore+0x49c",
    124: "SLDMFCU!uoRVAppearanceProperties::restore+0x7c",
    1244: "SLDMFCU!uoRVAppearanceProperties::restore+0x4dc",
    1328: "SLDMFCU!uoRVAppearanceProperties::restore+0x530",
    1344: "SLDMFCU!uoRVAppearanceProperties::restore+0x540",
    1360: "SLDMFCU!uoRVAppearanceProperties::restore+0x550",
    137: "SLDMFCU!uoRVAppearanceProperties::restore+0x89",
    1376: "SLDMFCU!uoRVAppearanceProperties::restore+0x560",
    1392: "SLDMFCU!uoRVAppearanceProperties::restore+0x570",
    1408: "SLDMFCU!uoRVAppearanceProperties::restore+0x580",
    1424: "SLDMFCU!uoRVAppearanceProperties::restore+0x590",
    1440: "SLDMFCU!uoRVAppearanceProperties::restore+0x5a0",
    1456: "SLDMFCU!uoRVAppearanceProperties::restore+0x5b0",
    1472: "SLDMFCU!uoRVAppearanceProperties::restore+0x5c0",
    1488: "SLDMFCU!uoRVAppearanceProperties::restore+0x5d0",
    150: "SLDMFCU!uoRVAppearanceProperties::restore+0x96",
    1504: "SLDMFCU!uoRVAppearanceProperties::restore+0x5e0",
    1520: "SLDMFCU!uoRVAppearanceProperties::restore+0x5f0",
    1536: "SLDMFCU!uoRVAppearanceProperties::restore+0x600",
    1552: "SLDMFCU!uoRVAppearanceProperties::restore+0x610",
    1568: "SLDMFCU!uoRVAppearanceProperties::restore+0x620",
    1584: "SLDMFCU!uoRVAppearanceProperties::restore+0x630",
    1600: "SLDMFCU!uoRVAppearanceProperties::restore+0x640",
    1616: "SLDMFCU!uoRVAppearanceProperties::restore+0x650",
    163: "SLDMFCU!uoRVAppearanceProperties::restore+0xa3",
    1632: "SLDMFCU!uoRVAppearanceProperties::restore+0x660",
    1648: "SLDMFCU!uoRVAppearanceProperties::restore+0x670",
    1664: "SLDMFCU!uoRVAppearanceProperties::restore+0x680",
    1680: "SLDMFCU!uoRVAppearanceProperties::restore+0x690",
    176: "SLDMFCU!uoRVAppearanceProperties::restore+0xb0",
    189: "SLDMFCU!uoRVAppearanceProperties::restore+0xbd",
    202: "SLDMFCU!uoRVAppearanceProperties::restore+0xca",
    215: "SLDMFCU!uoRVAppearanceProperties::restore+0xd7",
    228: "SLDMFCU!uoRVAppearanceProperties::restore+0xe4",
    257: "SLDMFCU!uoRVAppearanceProperties::restore+0x101",
    270: "SLDMFCU!uoRVAppearanceProperties::restore+0x10e",
    334: "SLDMFCU!uoRVAppearanceProperties::restore+0x14e",
    363: "SLDMFCU!uoRVAppearanceProperties::restore+0x16b",
    376: "SLDMFCU!uoRVAppearanceProperties::restore+0x178",
    389: "SLDMFCU!uoRVAppearanceProperties::restore+0x185",
    402: "SLDMFCU!uoRVAppearanceProperties::restore+0x192",
    435: "SLDMFCU!uoRVAppearanceProperties::restore+0x1b3",
    448: "SLDMFCU!uoRVAppearanceProperties::restore+0x1c0",
    46: "SLDMFCU!uoRVAppearanceProperties::restore+0x2e",
    59: "SLDMFCU!uoRVAppearanceProperties::restore+0x3b",
    604: "SLDMFCU!uoRVAppearanceProperties::restore+0x25c",
    617: "SLDMFCU!uoRVAppearanceProperties::restore+0x269",
    630: "SLDMFCU!uoRVAppearanceProperties::restore+0x276",
    795: "SLDMFCU!uoRVAppearanceProperties::restore+0x31b",
    811: "SLDMFCU!uoRVAppearanceProperties::restore+0x32b",
    827: "SLDMFCU!uoRVAppearanceProperties::restore+0x33b",
    843: "SLDMFCU!uoRVAppearanceProperties::restore+0x34b",
    85: "SLDMFCU!uoRVAppearanceProperties::restore+0x55",
    902: "SLDMFCU!uoRVAppearanceProperties::restore+0x386",
    915: "SLDMFCU!uoRVAppearanceProperties::restore+0x393",
    940: "SLDMFCU!uoRVAppearanceProperties::restore+0x3ac",
    956: "SLDMFCU!uoRVAppearanceProperties::restore+0x3bc",
    972: "SLDMFCU!uoRVAppearanceProperties::restore+0x3cc",
    98: "SLDMFCU!uoRVAppearanceProperties::restore+0x62",
    988: "SLDMFCU!uoRVAppearanceProperties::restore+0x3dc",
}
